version: "3.7"
services:
  auth-test:
    build:
      context: ./auth-webhook
      dockerfile: Dockerfile
    environment:
      DB_HOST: 172.17.0.2
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - '7321:8080'